apiVersion: v1
kind: Secret
type: Opaque
data:
  aws_access_key_id: QVNJQVJRWllHUE5XSVFGM1NFRTc=
  aws_secret_access_key: SzZCdnByYm85SnBrTHVTQXJic25yQVpTOWd4OE9oeGtuS0JwUXpzMQ==
metadata:
  name: aws-secret
