apiVersion: v1
kind: Secret
type: Opaque
data:
  aws_access_key_id: QVNJQVJRWllHUE5XSVFGM1NFRTc=
  aws_secret_access_key: SzZCdnByYm85SnBrTHVTQXJic25yQVpTOWd4OE9oeGtuS0JwUXpzMQ==
  credentials: W2RlZmF1bHRdDQphd3NfYWNjZXNzX2tleV9pZD1BU0lBUlFaWUdQTldMMjNYSklISg0KYXdzX3NlY3JldF9hY2Nlc3Nfa2V5PStvWEl2RUhNZFlvVTBiaERVTUdmY3c3N2laclJGZmJESllCaDdZYmUNCmF3c19zZXNzaW9uX3Rva2VuPUZ3b0daWEl2WVhkekVKWC8vLy8vLy8vLy93RWFETGdUOWFuWXZ5K3BHZzZIMmlMVkFUQUZWZGlQdnpqaHExWk1qSTd6U09VU0h3NTBWdndvZ0NOMTVYcWVYZU5hTzdaRnVnd1lRZ1E1eFdUbStVNi83enlDQVFwQm82aGRnZG5Qbk5hcG1nNEpVK0VCbjdObFZtdCthYzFZblk2ZmdqUmV4eENJd3ByK1pmWVJ4Vk1xbWo4SWhwanZJOWhtQVpZQ2M5Q3FGbVhWOUVaVmkrOVJPaWhuVjdObjJIYjE2RDZqVzh6YTFrMFMrS0dEUHdZZHFsdVNXd3pqajJzVFdqZWNrKzdKUkRwNlNOTHJnZmpaZVN1bGtsOXd2blJUZFJRODJOS2txYUZWdjhKZUE5dW05d01zNDAwM1AwQ3NZK2FyaXhQN3dRWGdmckRTL1NpanlLZVJCakl0a1Z5TDJzbGIzT3JtRUkvWkQ3cVprNE9QeXd1WDNiRExMQ0QvaVJvWUFuaDJLK3c0UEN3K1k1cFp3VG5y

metadata:
  name: aws-secret
