version: "4"
services:
  reverseproxy:
      image: reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-user:
    image: udagram-api-user
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 35725540 
      POSTGRES_DB: postgres 
      POSTGRES_HOST: my-104807693164-rds-proj3.conjkflcqheq.ap-southeast-1.rds.amazonaws.com
      AWS_REGION: ap-southeast-1 
      AWS_PROFILE: default
      AWS_BUCKET: my-104807693164-bucket-proj3
      JWT_SECRET: testing
      URL: "http://localhost:8100"
  backend-feed:
    image: udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 35725540 
      POSTGRES_DB: postgres
      POSTGRES_HOST: my-104807693164-rds-proj3.conjkflcqheq.ap-southeast-1.rds.amazonaws.com
      AWS_REGION: ap-southeast-1
      AWS_PROFILE: default
      AWS_BUCKET: my-104807693164-bucket-proj3
      JWT_SECRET: testing
      URL: "http://localhost:8100"
  frontend:
    image: udagram-frontend:local
    ports:
      - "8100:80"