apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy-app
  labels:
    run: udagram-reverseproxy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-reverseproxy-app
  template:
    metadata:
      labels:
        app: udagram-reverseproxy-app
    spec:
      containers:
      - name: udagram-reverseproxy
        image: huekiet/udagram-reverseproxy
        ports:
        - containerPort: 8080

